### ISSUE TITLE
Was willst Du erreichen?

### ISSUE THREAD

**Issue by JonathanBecks** [mietzen/python-fritz-advanced-thermostat#3]
Hey Nils,

cooles Repo, dass du da hast. Ich wollte genau das selbe bauen. Aber bei deinem Repo gab's Probleme mit dem Chrome Driver.

Ich bin jetzt auf das Repo FritzConnect gestoßen, dass sich an die offiziellen AVM API hält: https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AHA-HTTP-Interface.pdf

Hier ist es super einfach die Soll Temperatur hoch zu stellen:

`from fritzconnection import FritzConnection

Fritz_IP_ADDRESS = '192.168.178.1'
Passwort='xxx???'

fc = FritzConnection(address=Fritz_IP_ADDRESS, user='monitoring', password=Passwort)
state = fc.call_action("WLANConfiguration1","GetInfo")
print(state)

fc.call_http("getdevicelistinfos")
#set heat to 25 Celsius
fc.call_http("sethkrtsoll",ain='13979 xxx', param=50.0)`

vielleicht hilft dir das weiter?

**Comment by mietzen** [comment]
Die Probleme mit dem Chromedriver liegen an Selenium, ich habe jetzt wieder auf 4.10 runtergezogen, dass Problem tritt nur unter ARM. Die soll Temperatur zu ändern ist für mich keine Lösung, ich will, dass das Thermostat die richtige Temperatur anzeigt. Das lässt sich nur über den offset einstellen, welcher nicht über die offizielle API eingestellt werden kann.Am 13.09.2023 um 19:54 schrieb JonathanBecks ***@***.***>:﻿
Hey Nils,
cooles Repo, dass du da hast. Ich wollte genau das selbe bauen. Aber bei deinem Repo gab's Probleme mit dem Chrome Driver.
Ich bin jetzt auf das Repo FritzConnect gestoßen, dass sich an die offiziellen AVM API hält: https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AHA-HTTP-Interface.pdf
Hier ist es super einfach die Soll Temperatur hoch zu stellen:
`from fritzconnection import FritzConnection
Fritz_IP_ADDRESS = '192.168.178.1'
Passwort='xxx???'
fc = FritzConnection(address=Fritz_IP_ADDRESS, user='monitoring', password=Passwort)
state = fc.call_action("WLANConfiguration1","GetInfo")
print(state)
fc.call_http("getdevicelistinfos")
#set heat to 25 Celsius
fc.call_http("sethkrtsoll",ain='13979 xxx', param=50.0)`
vielleicht hilft dir das weiter?

**Comment by JonathanBecks** [comment]
Danke für die Antwort! ja, macht Sinn.
Vielleicht sollten wir bei Alm einfach einen Request stellend ass sie neben der "sethkrtsoll" auch die "sethkrtist" Methode zur Verfügung stellen. Ich werde dein Projekt auf jeden Fall im Auge behalten! 

LG!
